"""Offline tests for the pinned+hashed lockfiles (Story 10.40 / SEC-13, SEC-14).

There is no feature code to test-drive here — the story adds
``requirements.lock`` / ``requirements-dev.lock`` (generated by
``pip-compile --generate-hashes``) plus CI wiring. The executable spec for a
config story like this is the CI gate suite itself (ruff/mypy/coverage,
reproducible installs, ``pip-audit``) — see README.md's "Regenerating the
lockfile" section for how those are exercised. This module is the smoke test
that keeps the *committed lockfiles* themselves honest: every dependency
declared in pyproject.toml is represented and hash-pinned, so a PR that edits
pyproject.toml without regenerating the lockfile fails loudly here instead of
silently drifting until CI's ``--require-hashes`` install breaks.
"""

import re
from pathlib import Path

import depcheck

_REPO_ROOT = Path(__file__).resolve().parent
_RUNTIME_LOCK = _REPO_ROOT / "requirements.lock"
_DEV_LOCK = _REPO_ROOT / "requirements-dev.lock"
_AUDIT_LOCK = _REPO_ROOT / "requirements-audit.lock"

# Matches a top-level pinned requirement line, e.g. "python-dotenv==1.2.2 \".
# Continuation lines (hashes, "# via ...") are indented and don't match.
# Assumes every entry is a plain `name==version` pin, which holds for every
# dependency this project declares today. A future VCS/URL requirement
# (`pkg @ git+https://...`) or environment-marker line wouldn't match this
# pattern and would be silently excluded from the parity/hash checks below
# rather than raising — if pyproject.toml ever grows one, extend this regex
# (or add a dedicated case) instead of assuming it's covered.
_PINNED_LINE_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==(\S+?)\s*\\?\s*$", re.MULTILINE)


def _normalize(dist_name: str) -> str:
    """PEP 503 normalization: lowercase, underscores/dots -> hyphens."""
    return re.sub(r"[-_.]+", "-", dist_name).lower()


def _parse_lockfile(path: Path) -> dict[str, str]:
    """Return {normalized dist name: pinned version} for a pip-compile lockfile."""
    text = path.read_text(encoding="utf-8")
    return {_normalize(name): version for name, version in _PINNED_LINE_RE.findall(text)}


def _declared_dist_names(groups: dict[str, list[str]], *group_names: str) -> set[str]:
    names = set()
    for group in group_names:
        for requirement in groups.get(group, []):
            names.add(_normalize(depcheck.distribution_name(requirement)))
    return names


# --- lockfiles exist and are non-trivial ------------------------------------


def test_runtime_lockfile_exists_and_is_pinned() -> None:
    assert _RUNTIME_LOCK.is_file()
    assert len(_parse_lockfile(_RUNTIME_LOCK)) > 0


def test_dev_lockfile_exists_and_is_pinned() -> None:
    assert _DEV_LOCK.is_file()
    assert len(_parse_lockfile(_DEV_LOCK)) > 0


def test_audit_lockfile_exists_pins_pip_audit_and_is_pinned() -> None:
    # requirements-audit.lock pins the CI dependency-audit job's own scanner
    # (pip-audit) — added in review follow-up so the auditor itself can't be
    # an unpinned, unhashed supply-chain gap in the job that closes one.
    assert _AUDIT_LOCK.is_file()
    pinned = _parse_lockfile(_AUDIT_LOCK)
    assert len(pinned) > 0
    assert "pip-audit" in pinned


# --- every declared dependency is represented in the lockfile ---------------


def test_every_runtime_dependency_is_pinned_in_both_lockfiles() -> None:
    groups = depcheck.load_declared_dependencies()
    declared = _declared_dist_names(groups, "project")

    runtime_pinned = set(_parse_lockfile(_RUNTIME_LOCK))
    dev_pinned = set(_parse_lockfile(_DEV_LOCK))

    missing_runtime = declared - runtime_pinned
    missing_dev = declared - dev_pinned
    assert not missing_runtime, f"requirements.lock is missing: {sorted(missing_runtime)}"
    assert not missing_dev, f"requirements-dev.lock is missing: {sorted(missing_dev)}"


def test_shared_packages_pin_the_same_version_in_both_lockfiles() -> None:
    # requirements.lock and requirements-dev.lock are each generated by their
    # own `pip-compile` invocation (README.md's "Regenerating the lockfile"
    # section) — nothing forces the two resolves to agree on a package they
    # both pin. A silent divergence here would mean only one of the two
    # versions is what CI's `dependency-audit` job actually CVE-scans for a
    # shared dependency, undermining the "fresh install yields identical
    # versions" guarantee for whichever lockfile isn't audited.
    runtime_pinned = _parse_lockfile(_RUNTIME_LOCK)
    dev_pinned = _parse_lockfile(_DEV_LOCK)

    shared = set(runtime_pinned) & set(dev_pinned)
    assert shared, "expected at least one package pinned in both lockfiles"
    mismatched = {
        name: (runtime_pinned[name], dev_pinned[name])
        for name in shared
        if runtime_pinned[name] != dev_pinned[name]
    }
    assert not mismatched, f"version mismatch between lockfiles: {mismatched}"


def test_every_dev_dependency_is_pinned_in_dev_lockfile_only() -> None:
    groups = depcheck.load_declared_dependencies()
    declared_dev = _declared_dist_names(groups, "dev")

    dev_pinned = set(_parse_lockfile(_DEV_LOCK))
    missing = declared_dev - dev_pinned
    assert not missing, f"requirements-dev.lock is missing dev deps: {sorted(missing)}"

    # The runtime-only lockfile must NOT pull in dev-only tooling (pytest,
    # ruff, mypy, ...) — that's the whole point of shipping two lockfiles.
    runtime_pinned = set(_parse_lockfile(_RUNTIME_LOCK))
    declared_runtime = _declared_dist_names(groups, "project")
    dev_only = declared_dev - declared_runtime
    leaked = dev_only & runtime_pinned
    assert not leaked, f"requirements.lock unexpectedly pins dev-only deps: {sorted(leaked)}"


# --- every pinned entry is hash-verified ------------------------------------


def _blocks(text: str) -> list[str]:
    """Split a pip-compile lockfile into one chunk per top-level pinned line."""
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if _PINNED_LINE_RE.match(line)]
    blocks = []
    for idx, start in enumerate(starts):
        end = starts[idx + 1] if idx + 1 < len(starts) else len(lines)
        blocks.append("\n".join(lines[start:end]))
    return blocks


def test_runtime_lockfile_every_entry_carries_a_hash() -> None:
    blocks = _blocks(_RUNTIME_LOCK.read_text(encoding="utf-8"))
    assert blocks, "expected at least one pinned entry"
    unhashed = [b.splitlines()[0] for b in blocks if "--hash=sha256:" not in b]
    assert not unhashed, f"unhashed lockfile entries: {unhashed}"


def test_dev_lockfile_every_entry_carries_a_hash() -> None:
    blocks = _blocks(_DEV_LOCK.read_text(encoding="utf-8"))
    assert blocks, "expected at least one pinned entry"
    unhashed = [b.splitlines()[0] for b in blocks if "--hash=sha256:" not in b]
    assert not unhashed, f"unhashed lockfile entries: {unhashed}"


def test_audit_lockfile_every_entry_carries_a_hash() -> None:
    blocks = _blocks(_AUDIT_LOCK.read_text(encoding="utf-8"))
    assert blocks, "expected at least one pinned entry"
    unhashed = [b.splitlines()[0] for b in blocks if "--hash=sha256:" not in b]
    assert not unhashed, f"unhashed lockfile entries: {unhashed}"
