"""Contract test: every GraphQL operation the package sends is checked against a
committed, generated snapshot of the pinned Admin API schema (Story 9.16,
generalizing Stories 9.12, 9.14 and 9.18).

**What this suite proves, and what it does not.** It has two legs:

- ``test_document_matches_pinned_schema`` validates every operation document
  against the snapshot. A failure means the document has DRIFTED: it references
  something the pinned schema does not declare, not even as deprecated. That is
  the class behind every real outage this project has had (``priceRules``,
  ``referringSite``, ``node { ... on Job }``). It is NOT proof the operation is
  broken live. The snapshot can be stale, or the drift can be harmless.
  Confirm by executing the operation before calling a tool broken.
- ``test_emitted_payload_is_accepted_by_pinned_schema`` coerces the variables
  the operations layer actually emits. Document validation cannot see inside an
  input object supplied as a variable (see
  ``test_document_validation_alone_cannot_see_inside_a_variable``). A coercion
  failure means the payload itself is rejected, which is a real break.

Neither leg proves an operation WORKS live. Both check shape against a
recorded schema. Business rules ("Context can't be blank") and semantics
(``productUpdate`` replacing a nested input wholesale; see
``test_nested_input_writes.py``) are out of reach of any schema check.

**The snapshot.** ``admin_schema_snapshot.graphql`` beside this module is
GENERATED by ``tests/support/admin_schema_snapshot.py`` from a live
introspection at the SERVED API version, trimmed to what the discovered
documents reach. Do not hand-edit it. Its input objects carry their real field
sets, and its arguments and input fields include deprecated ones.

**Why deprecated input values matter (Story 9.16).** Story 9.18 read
``productUpdate(input:)`` and ``WebhookSubscriptionInput.callbackUrl`` as
removed on 2026-01, and saw Shopify accept ``input:`` anyway. Both are
DEPRECATED, not removed. The standard introspection query leaves deprecated
arguments and input fields out, so a snapshot built from it rejects operations
Shopify still serves. A query-only probe against the live store on 2026-09-16
showed that Shopify does reject an argument it does not declare
(``Field 'shop' doesn't accept argument 'bogusArg'``).
``test_snapshot_carries_deprecated_input_values`` pins this.

**Refreshing.** See README, "Refreshing the Admin API schema snapshot":
``REFRESH_ADMIN_SCHEMA_SNAPSHOT=1 pytest tests/live/test_admin_schema_snapshot.py``
after bumping ``SHOPIFY_API_VERSION``, or when a document starts selecting
something the snapshot lacks.
"""

import importlib
import inspect
import pkgutil
import sys
from collections.abc import Callable
from datetime import date
from typing import Any

import pytest
from graphql import (
    GraphQLInputObjectType,
    OperationDefinitionNode,
    build_schema,
    get_named_type,
    parse,
    type_from_ast,
    validate,
)
from graphql.execution.values import get_variable_values
from graphql.validation import NoDeprecatedCustomRule

import shopify_mcp.shopify.queries as queries_package
from shopify_mcp.shopify.operations import catalog_hygiene as hygiene_ops
from shopify_mcp.shopify.operations import collections as collection_ops
from shopify_mcp.shopify.operations import inventory as inventory_ops
from shopify_mcp.shopify.operations import products as ops
from shopify_mcp.shopify.operations import publications as publication_ops
from shopify_mcp.shopify.operations import webhooks as webhook_ops
from shopify_mcp.shopify.queries.products import UPDATE_PRODUCT
from shopify_mcp.shopify.queries.webhooks import CREATE_WEBHOOK
from tests.support.admin_schema_snapshot import (
    SNAPSHOT_PATH,
    all_documents,
    builder_documents,
    discover_documents,
    generate_sdl,
    read_snapshot_header,
)

_SNAPSHOT_TEXT = SNAPSHOT_PATH.read_text(encoding="utf-8")
_API_VERSION, _CAPTURED = read_snapshot_header(_SNAPSHOT_TEXT)

# Imported by test_nested_input_writes.py (Story 9.19). Keep the name.
_SCHEMA = build_schema(_SNAPSHOT_TEXT)

_DOCUMENTS = all_documents()
_LABEL_BY_TEXT = {text: label for label, text in _DOCUMENTS.items()}

# 2026-09-16: 66 distinct constants (58 in shopify/queries, 7 in
# tools/media/_graphql.py, 1 in client.py) + 10 builder outputs.
_DOCUMENT_FLOOR = 76

# Drift the validation leg reports on an operation Shopify has been confirmed
# to serve anyway. {label: (reason, date last confirmed served live, ISO)}.
# Empty on landing: every document matches the pinned schema. An entry must be
# re-confirmed (and re-dated) whenever the snapshot is refreshed, because a
# refresh is the only moment the fact can change; see
# test_served_despite_drift_entries_are_dated_and_current.
_SERVED_DESPITE_DRIFT: dict[str, tuple[str, str]] = {}

# Deprecated (type, field / argument / enum value) usages across all documents,
# measured 2026-09-16 against 2026-01. They are the likeliest next removals, and
# the list lives in docs/tech-debt.md. May fall freely; raising it is a
# deliberate edit.
_DEPRECATED_USAGE_CEILING = 30


def _operation(text: str) -> OperationDefinitionNode:
    return next(d for d in parse(text).definitions if isinstance(d, OperationDefinitionNode))


# ===========================================================================
# Discovery: the suite cannot pass by checking nothing
# ===========================================================================


def test_discovery_finds_at_least_the_pinned_number_of_documents():
    assert len(_DOCUMENTS) >= _DOCUMENT_FLOOR, (
        f"Expected at least {_DOCUMENT_FLOOR} GraphQL operations, discovered "
        f"{len(_DOCUMENTS)}. {_DOCUMENT_FLOOR} is the count this suite shipped with "
        "(Story 9.16), not a floor with independent meaning. If documents were "
        "genuinely removed, lower it. Otherwise the discovery sweep is broken."
    )


def test_each_document_is_checked_once_under_its_defining_module():
    """``shopify/queries`` constants are re-exported through ``shopify/operations``
    AND ``tools``, so a naive sweep sees each one about three times. Discovery
    labels a document by the module that ASSIGNS it, and only there. Operations
    outside ``shopify/queries`` must still be found."""
    labels = set(_DOCUMENTS)
    assert "shopify_mcp.shopify.queries.catalog_hygiene.GET_PRODUCT_CATEGORY" in labels
    assert [lbl for lbl in labels if lbl.endswith(".GET_PRODUCT_CATEGORY")] == [
        "shopify_mcp.shopify.queries.catalog_hygiene.GET_PRODUCT_CATEGORY"
    ]
    assert "shopify_mcp.client.JOB_STATUS_QUERY" in labels
    assert sum(lbl.startswith("shopify_mcp.tools.media._graphql.") for lbl in labels) == 7
    assert len(set(_DOCUMENTS.values())) == len(_DOCUMENTS)


def test_a_constant_in_a_file_that_does_not_exist_yet_is_discovered_and_checked(
    tmp_path, monkeypatch
):
    """Proves the sweep is repo-wide by construction, not by a file list.

    Written against a synthetic package: the real tree is (correctly) clean, so
    asserting on it would pass whether or not discovery reaches a new file. The
    package also re-exports the constant from a second module, to prove the
    new document is reported once, under the module that defines it."""
    package = tmp_path / "probe_9_16"
    (package / "deep").mkdir(parents=True)
    (package / "__init__.py").write_text("", encoding="utf-8")
    (package / "deep" / "__init__.py").write_text("", encoding="utf-8")
    (package / "deep" / "new_queries.py").write_text(
        'NEW_QUERY = "query New($id: ID!) { product(id: $id) { notARealField } }"\n'
        'not_upper = "query Hidden { shop { id } }"\n'
        'PROSE = "Not GraphQL at all"\n',
        encoding="utf-8",
    )
    (package / "reexport.py").write_text(
        "from probe_9_16.deep.new_queries import NEW_QUERY\n", encoding="utf-8"
    )
    monkeypatch.syspath_prepend(str(tmp_path))
    try:
        found = discover_documents(tmp_path, "probe_9_16")
    finally:
        for name in [m for m in sys.modules if m.startswith("probe_9_16")]:
            del sys.modules[name]

    assert list(found) == ["probe_9_16.deep.new_queries.NEW_QUERY"]
    errors = validate(_SCHEMA, parse(found["probe_9_16.deep.new_queries.NEW_QUERY"]))
    assert any("notARealField" in str(e) for e in errors), errors


def test_every_query_builder_is_registered():
    """A document assembled at call time is invisible to the constant sweep, so
    every ``_build_*`` function in ``shopify_mcp.shopify.queries`` must have
    outputs in ``builder_documents()``. Scoped to ``shopify.queries`` on purpose:
    ``_build_*`` functions elsewhere build regexes and payloads, not GraphQL."""
    registered = builder_documents()
    builders = []
    for info in pkgutil.iter_modules(queries_package.__path__):
        module = importlib.import_module(f"{queries_package.__name__}.{info.name}")
        for name, function in inspect.getmembers(module, inspect.isfunction):
            if name.startswith("_build_") and function.__module__ == module.__name__:
                builders.append(f"{module.__name__}.{name}")
    assert len(builders) >= 4, f"builder scan found only {builders}; is it still looking?"
    unregistered = [b for b in builders if not any(lbl.startswith(f"{b}[") for lbl in registered)]
    assert unregistered == [], (
        f"{unregistered} build GraphQL at call time but have no entry in "
        "tests/support/admin_schema_snapshot.py:builder_documents()"
    )


# ===========================================================================
# The snapshot itself
# ===========================================================================


def test_snapshot_header_names_the_served_version_and_capture_date():
    assert _API_VERSION.count("-") == 1 and _API_VERSION.replace("-", "").isdigit(), _API_VERSION
    date.fromisoformat(_CAPTURED)


_GENERATOR_FIXTURE_SDL = """
schema { query: Root mutation: Mutation }
interface Node { id: ID! }
type Thing implements Node { id: ID! name: String unused: Int }
type Other implements Node { id: ID! size: Int }
type Stray { id: ID! }
union Result = Thing | Other | Stray
enum Colour { RED GREEN BLUE @deprecated(reason: "gone soon") }
input Nested { a: String b: Int }
input ThingInput { name: String nested: Nested colour: Colour }
type Root {
  node(id: ID!): Node
  search(term: String, legacy: String @deprecated(reason: "use term")): [Result!]!
  unused: String
}
type Mutation { thingUpdate(input: ThingInput!): Thing }
"""


def test_generator_trims_to_what_documents_reach():
    """Offline check of the generator itself. The committed snapshot is only ever
    regenerated by the live runner, so without this a generator regression (a
    placeholder input object, a dropped deprecated argument) would pass offline."""
    full = build_schema(_GENERATOR_FIXTURE_SDL)
    documents = [
        "query A($id: ID!) { node(id: $id) { id ... on Thing { name } } }",
        'query B { search(term: "x") { ... on Other { size } } }',
        "mutation C($input: ThingInput!) { thingUpdate(input: $input) { id } }",
    ]
    sdl = generate_sdl(full, documents)

    assert sdl == generate_sdl(full, list(reversed(documents))), "not order-independent"
    trimmed = build_schema(sdl)
    assert all(validate(trimmed, parse(d)) == [] for d in documents)
    # Input objects in full, recursively, with enums in full (deprecations kept).
    assert set(trimmed.get_type("ThingInput").fields) == {"name", "nested", "colour"}
    assert set(trimmed.get_type("Nested").fields) == {"a", "b"}
    assert trimmed.get_type("Colour").values["BLUE"].deprecation_reason == "gone soon"
    # Full argument signatures, deprecated arguments included.
    assert trimmed.query_type.fields["search"].args["legacy"].deprecation_reason == "use term"
    # Only selected fields; an interface's fields reach every implementer.
    assert set(trimmed.get_type("Thing").fields) == {"id", "name"}
    assert set(trimmed.get_type("Other").fields) == {"id", "size"}
    assert "unused" not in trimmed.query_type.fields
    # Unions keep only reached members.
    assert [t.name for t in trimmed.get_type("Result").types] == ["Other", "Thing"]
    assert trimmed.get_type("Stray") is None


def test_snapshot_carries_deprecated_input_values():
    """Guards against a refresh that forgets ``input_value_deprecation=True``.

    Without deprecated input values the snapshot rejects ``productUpdate(input:)``,
    an argument Shopify still serves. That false drift report is what Story 9.18
    read as a removed argument that was still served."""
    product_update = _SCHEMA.mutation_type.fields["productUpdate"]
    assert product_update.args["input"].deprecation_reason
    webhook_input = _SCHEMA.get_type("WebhookSubscriptionInput")
    assert isinstance(webhook_input, GraphQLInputObjectType)
    assert webhook_input.fields["callbackUrl"].deprecation_reason


# ===========================================================================
# LEG 1: document matches the pinned schema (drift detector)
# ===========================================================================


def _drift_message(label: str, errors: list) -> str:
    return (
        f"{label} has DRIFTED from the pinned Admin API schema ({_API_VERSION}, "
        f"captured {_CAPTURED}): {[e.message for e in errors]}\n"
        "This does NOT prove the operation is broken live. Confirm by executing "
        "it before calling any tool broken: run a read with real variables, or "
        "send a mutation against an id that cannot exist (e.g. "
        "gid://shopify/Product/1). Shopify rejects an invalid document before "
        "executing anything, and answers a valid one with an ordinary userErrors "
        "entry.\n"
        "If the snapshot is stale, refresh it (README: 'Refreshing the Admin API "
        "schema snapshot'). If Shopify serves the operation anyway, record it in "
        "_SERVED_DESPITE_DRIFT with today's date."
    )


@pytest.mark.parametrize("label", sorted(_DOCUMENTS))
def test_document_matches_pinned_schema(label):
    errors = validate(_SCHEMA, parse(_DOCUMENTS[label]))
    if label in _SERVED_DESPITE_DRIFT:
        assert errors, (
            f"{label} now matches the pinned schema: remove its _SERVED_DESPITE_DRIFT entry"
        )
        return
    assert errors == [], _drift_message(label, errors)


def test_validator_catches_a_field_removed_from_the_schema():
    """Proves the harness is not a no-op: ``priceRules`` was removed from
    QueryRoot, the exact shape of bug this suite exists to catch."""
    bad_query = "query Bad($first: Int!) { priceRules(first: $first) { nodes { id } } }"
    errors = validate(_SCHEMA, parse(bad_query))
    assert any("priceRules" in str(e) for e in errors)


def test_validator_catches_referring_site_removed_from_order():
    bad_query = "query Bad { orders(first: 1) { nodes { referringSite } } }"
    errors = validate(_SCHEMA, parse(bad_query))
    assert any("referringSite" in str(e) for e in errors)


def test_validator_catches_price_rule_create_removed_from_schema():
    """Mutation side: ``priceRuleCreate`` is what broke ``create_discount_code``
    before Story 9.14 replaced it with ``discountCodeBasicCreate``."""
    bad_mutation = "mutation Bad { priceRuleCreate(priceRule: {}) { priceRule { id } } }"
    errors = validate(_SCHEMA, parse(bad_mutation))
    assert any("priceRuleCreate" in str(e) for e in errors)


def test_validator_rejects_an_argument_the_schema_does_not_declare():
    bad = (
        "mutation Bad($p: ProductUpdateInput) "
        "{ productUpdate(bogusArgument: $p) { product { id } } }"
    )
    errors = validate(_SCHEMA, parse(bad))
    # Anchored: graphql-core also reports the unused variable.
    assert any("Unknown argument 'bogusArgument'" in str(e) for e in errors), errors


def test_a_deprecated_argument_matches_but_is_reported_as_deprecated():
    """``productUpdate(input:)`` is deprecated on 2026-01, not removed. It must
    match the snapshot, because Shopify serves it, and the deprecation ratchet
    below must still see it."""
    old_shape = (
        "mutation Old($input: ProductInput) { productUpdate(input: $input) { product { id } } }"
    )
    assert validate(_SCHEMA, parse(old_shape)) == []
    deprecations = validate(_SCHEMA, parse(old_shape), [NoDeprecatedCustomRule])
    assert any("'input'" in str(e) and "productUpdate" in str(e) for e in deprecations), (
        deprecations
    )


def test_validator_catches_job_spread_inside_node():
    """``Job`` implements no interfaces on 2026-01, so ``node(id:) { ... on Job }``
    can never match. That was the one genuinely broken document of Story 9.18."""
    bad = "query Bad($id: ID!) { node(id: $id) { ... on Job { id done } } }"
    joined = " ".join(str(e) for e in validate(_SCHEMA, parse(bad)))
    assert "can never be of type 'Job'" in joined, joined


def test_the_node_control_is_live_so_the_job_test_cannot_pass_vacuously():
    """Spreading a type that DOES implement Node is accepted. If this fails,
    ``node(id:)`` is gone from the snapshot and the Job test above no longer
    tests what it claims."""
    good = "query Good($id: ID!) { node(id: $id) { ... on Product { id title } } }"
    assert validate(_SCHEMA, parse(good)) == []


def test_deprecated_usages_do_not_grow():
    usages = sorted(
        f"{label}: {error.message}"
        for label, text in _DOCUMENTS.items()
        for error in validate(_SCHEMA, parse(text), [NoDeprecatedCustomRule])
    )
    assert len(usages) <= _DEPRECATED_USAGE_CEILING, (
        f"{len(usages)} deprecated usages, ceiling {_DEPRECATED_USAGE_CEILING}. A new "
        "document uses a deprecated field, argument or enum value. Use its "
        "replacement, or raise the ceiling deliberately and record the usage in "
        "docs/tech-debt.md.\n" + "\n".join(usages)
    )


def _served_despite_drift_problems(
    entries: dict[str, tuple[str, str]], captured: str, labels: set[str]
) -> list[str]:
    problems = []
    for label, (reason, confirmed) in sorted(entries.items()):
        if label not in labels:
            problems.append(f"{label}: no such document")
        if not reason.strip():
            problems.append(f"{label}: no reason")
        try:
            confirmed_on = date.fromisoformat(confirmed)
        except ValueError:
            problems.append(f"{label}: {confirmed!r} is not a live-confirmation date")
            continue
        if confirmed_on < date.fromisoformat(captured):
            problems.append(
                f"{label}: last confirmed served {confirmed}, before the snapshot was "
                f"captured {captured}. Re-confirm it live and re-date it."
            )
    return problems


def test_served_despite_drift_entries_are_dated_and_current():
    """Only a dated, re-confirmed entry separates a verified exception from a
    silenced failure."""
    assert _served_despite_drift_problems(_SERVED_DESPITE_DRIFT, _CAPTURED, set(_DOCUMENTS)) == []


def test_the_served_despite_drift_check_rejects_bad_entries():
    """The check above is vacuous while the allowlist is empty, so prove it bites."""
    label = "shopify_mcp.client.JOB_STATUS_QUERY"
    problems = _served_despite_drift_problems(
        {
            label: ("served anyway", ""),
            "shopify_mcp.nowhere.GONE": ("", "2099-01-01"),
            "shopify_mcp.shopify.queries.orders.GET_ORDERS": ("served", "2000-01-01"),
        },
        "2026-09-16",
        set(_DOCUMENTS),
    )
    joined = "\n".join(problems)
    assert f"{label}: '' is not a live-confirmation date" in joined
    assert "GONE: no such document" in joined and "GONE: no reason" in joined
    assert "GET_ORDERS: last confirmed served 2000-01-01" in joined


# ===========================================================================
# LEG 2: emitted payload is accepted by the pinned schema (rejection = real break)
#
# ``graphql.validate`` reads the DOCUMENT. An input object supplied as a variable
# is opaque to it, which is how ``register_webhook`` validated clean while its
# payload was wrong (Story 9.18). So these call the real operations functions
# and coerce what they emit, rather than restating a payload literal (that would
# pin what the test author believed the code sends).
# ===========================================================================


class _CapturingClient:
    """Minimal GraphQLClient stand-in that records the (query, variables) sent."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, dict]] = []

    def execute(self, query: str, variables: dict | None = None) -> dict:
        self.calls.append((query, variables or {}))
        return {}


_PID = "6803111739545"
_GID = f"gid://shopify/Product/{_PID}"

_EMITTERS: dict[str, Callable[[_CapturingClient], Any]] = {
    "update_product_title": lambda c: ops.update_product_title(c, _PID, "T", "t-handle"),
    "update_product_description": lambda c: ops.update_product_description(c, _PID, "<p>d</p>"),
    "update_product_seo": lambda c: ops.update_product_seo(c, _PID, title="S", description="D"),
    "update_product_tags": lambda c: ops.update_product_tags(c, _PID, ["a", "b"]),
    "update_product_status": lambda c: ops.update_product_status(c, _PID, "ARCHIVED"),
    "update_product_category": lambda c: hygiene_ops.update_product_category(
        c, _GID, "gid://shopify/TaxonomyCategory/aa-1"
    ),
    "update_product_vendor": lambda c: hygiene_ops.update_product_vendor(c, _GID, "V"),
    "update_product_type": lambda c: hygiene_ops.update_product_type(c, _GID, "Tee"),
    "create_webhook": lambda c: webhook_ops.create_webhook(
        c, "ORDERS_CREATE", "https://example.com/hook", "JSON"
    ),
    "create_collection": lambda c: collection_ops.create_collection(
        c, title="T", handle="t", description_html="<p>d</p>"
    ),
    "update_collection": lambda c: collection_ops.update_collection(
        c, "gid://shopify/Collection/1", new_title="T", new_description="<p>d</p>"
    ),
    "publish": lambda c: publication_ops.publish(c, _GID, ["gid://shopify/Publication/1"]),
    "unpublish": lambda c: publication_ops.unpublish(c, _GID, ["gid://shopify/Publication/1"]),
    "update_inventory_item_tracked": lambda c: inventory_ops.update_inventory_item_tracked(
        c, "gid://shopify/InventoryItem/1", True
    ),
}

# Documents taking an input object whose payload is assembled OUTSIDE the
# operations layer (the tool builds it and the operations function forwards it
# verbatim), so no operations call here can emit the real thing. Recorded gaps,
# not coverage.
_PAYLOAD_BUILT_UPSTREAM: dict[str, str] = dict.fromkeys(
    (
        "shopify_mcp.shopify.queries.catalog_hygiene.METAFIELDS_DELETE_MUTATION",
        "shopify_mcp.shopify.queries.catalog_hygiene.METAFIELDS_SET_MUTATION",
        "shopify_mcp.shopify.queries.catalog_hygiene.PRODUCT_VARIANT_APPEND_MEDIA",
        "shopify_mcp.shopify.queries.catalog_hygiene.PRODUCT_VARIANT_DETACH_MEDIA",
        "shopify_mcp.shopify.queries.catalog_hygiene.UPDATE_PRODUCT_OPTION",
        "shopify_mcp.shopify.queries.catalog_hygiene.UPDATE_PRODUCT_VARIANTS_PRICING",
        "shopify_mcp.shopify.queries.discounts.CREATE_DISCOUNT_CODE_BASIC",
        "shopify_mcp.shopify.queries.inventory.SET_INVENTORY",
        "shopify_mcp.shopify.queries.products.UPDATE_PRODUCT_VARIANTS_POLICY",
    ),
    "payload built in the tool layer; the operations function forwards it",
) | dict.fromkeys(
    (
        "shopify_mcp.tools.media._graphql.PRODUCT_CREATE_MEDIA",
        "shopify_mcp.tools.media._graphql.PRODUCT_REORDER_MEDIA",
        "shopify_mcp.tools.media._graphql.PRODUCT_UPDATE_MEDIA",
        "shopify_mcp.tools.media._graphql.STAGED_UPLOADS_CREATE",
    ),
    "tools/media builds and executes these directly; there is no operations function",
)


def _emit(emitter: Callable[[_CapturingClient], Any]) -> tuple[str, dict]:
    client = _CapturingClient()
    emitter(client)
    assert len(client.calls) == 1, f"expected exactly one execute(), got {len(client.calls)}"
    return client.calls[0]


def _coerce(query: str, variables: dict) -> Any:
    """graphql-core 3.2 returns the coerced dict on success, or a list of
    GraphQLError on failure, so ``isinstance(..., dict)`` IS the verdict."""
    return get_variable_values(_SCHEMA, _operation(query).variable_definitions, variables)


def _coercion_errors(query: str, variables: dict) -> str:
    coerced = _coerce(query, variables)
    assert not isinstance(coerced, dict), f"expected coercion to fail, got {coerced!r}"
    return " ".join(str(e) for e in coerced)


@pytest.mark.parametrize("name", sorted(_EMITTERS))
def test_emitted_payload_is_accepted_by_pinned_schema(name):
    query, variables = _emit(_EMITTERS[name])
    assert query in _LABEL_BY_TEXT, f"{name} sent a document discovery does not know about"
    coerced = _coerce(query, variables)
    assert isinstance(coerced, dict), (
        f"{name}: the payload the operations layer emits is REJECTED by the pinned "
        f"schema ({_API_VERSION}): {[str(e) for e in coerced]}"
    )


def test_every_document_taking_an_input_object_is_emitted_or_a_recorded_gap():
    """A new write that sends an input object must join ``_EMITTERS`` or
    ``_PAYLOAD_BUILT_UPSTREAM``, so the coercion leg's coverage cannot shrink
    silently. The equality runs both ways, so a stale entry fails too."""

    def takes_input_object(text: str) -> bool:
        return any(
            isinstance(get_named_type(type_from_ast(_SCHEMA, v.type)), GraphQLInputObjectType)
            for v in _operation(text).variable_definitions or ()
        )

    taking = {label for label, text in _DOCUMENTS.items() if takes_input_object(text)}
    emitted = {_LABEL_BY_TEXT[_emit(emitter)[0]] for emitter in _EMITTERS.values()}
    assert not emitted & _PAYLOAD_BUILT_UPSTREAM.keys()
    assert taking == emitted | _PAYLOAD_BUILT_UPSTREAM.keys()


# ---- the discriminating negatives ------------------------------------------
#
# Without these, a coercion leg that silently accepted everything would pass.


def test_coercion_rejects_an_unsupplied_required_variable():
    """The old ``"input"`` payload key against the ``$product`` document leaves
    the variable unsupplied."""
    joined = _coercion_errors(UPDATE_PRODUCT, {"input": {"id": _GID, "title": "T"}})
    assert "$product" in joined
    assert "ProductUpdateInput!" in joined


def test_coercion_rejects_a_field_the_input_type_does_not_declare():
    joined = _coercion_errors(
        CREATE_WEBHOOK,
        {
            "topic": "ORDERS_CREATE",
            "webhookSubscription": {"uri": "https://example.com/hook", "bogusField": "x"},
        },
    )
    assert "bogusField" in joined
    assert "WebhookSubscriptionInput" in joined


def test_coercion_rejects_an_undeclared_field_in_a_nested_input_object():
    joined = _coercion_errors(
        UPDATE_PRODUCT, {"product": {"id": _GID, "seo": {"title": "S", "bogusField": "x"}}}
    )
    assert "bogusField" in joined
    assert "SEOInput" in joined


def test_document_validation_alone_cannot_see_inside_a_variable():
    """Pins WHY leg 2 exists, so nobody deletes it as redundant: the same broken
    payload is invisible to ``validate()`` (which takes no variables) and
    rejected by coercion."""
    broken_payload = {
        "topic": "ORDERS_CREATE",
        "webhookSubscription": {"bogusField": "https://example.com/hook", "format": "JSON"},
    }
    assert validate(_SCHEMA, parse(CREATE_WEBHOOK)) == []
    assert not isinstance(_coerce(CREATE_WEBHOOK, broken_payload), dict)
